arch: amd64
os: linux
dist: focal

language: bash

services:
  - docker

before_install:
  - docker build --pull --rm -f "Dockerfile" -t dcr-l2jmobius:latest .

install:
  - docker run --rm -it -v /root/compiled:/root/compiled dcr-l2jmobius:latest L2J_Mobius_CT_2.6_HighFive