arch: amd64
os: linux
dist: focal

language: bash

services:
  - docker

before_install:
  - docker build --pull --rm -f "Dockerfile" -t l2jmobius_docker:latest .

install:
  - docker run --rm -it -v /root/compiled:/root/compiled l2jmobius_docker:latest L2J_Mobius_Classic_Interlude
